# This file tells Netlify how to build Twelvety
# If you aren't using Netlify then you can delete this file

[dev]
  command = "npm run dev"
  publish = "dist"

[build]
  command = "npm run build"
  publish = "dist"

[context.production.environment]
    ELEVENTY_ENV = "production"

[[redirects]]
    from = "*"
    to = "/404"
    status = 404
